# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ROCconvexhull <- function(scores, classes) {
    .Call(`_proftree_ROCconvexhull`, scores, classes)
}

empChurnCpp <- function(scores, classes, alpha, beta, clv, d, f) {
    .Call(`_proftree_empChurnCpp`, scores, classes, alpha, beta, clv, d, f)
}

